### ISSUE TITLE
Use command line interface

### ISSUE THREAD

**Issue by vkaelin** [dil-classroom/projet-friedli_jaquier_kaelin_pavicevic#17]
**Description:**

As a user, I would like to be able to start the application directly from the terminal.

Repository to get some idea of how to do it: https://github.com/dil-classroom/statique

**Tasks**

- [x] Add dependency in the pom.xml to create a zip
- [x] Create assembly.xml file to configure the previously added zip
- [x] Create bash file to execute the .jar
- [x] Add the bash file to environnement variable
- [x] Document how to use the CLI in the readme

**Duration:**

- Optimistic: 1h
- Pessimistic: 3h
- Expected: 2h

**Requirements:**
- #25
