### ISSUE TITLE
Improve continuous integration

### ISSUE THREAD

**Issue by Lazzzer** [dil-classroom/projet-friedli_jaquier_kaelin_pavicevic#20]
**Description:**

As a developer, I would like that the pull requests can only be merged when the code compiles and the tests pass. The pull requests should not be merged when the code is not correctly formated.

Useful links:
- https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
- https://github.com/diffplug/spotless/tree/main/plugin-maven

**Tasks:**
- [x] Setup a GitHub Action file
- [x] Add a job checking the compilation of the code
- [x] Add a job checking if the tests pass
- [x] Add a job checking the formatting of the code

**Duration:**

- Optimistic: 1h30
- Pessimistic: 3h00
- Expected: 2h30

**Requirements:**

- #19
