### ISSUE TITLE
Template engine: create HTML components

### ISSUE THREAD

**Issue by vkaelin** [dil-classroom/projet-friedli_jaquier_kaelin_pavicevic#40]
**Description:**

As a user, I would like to be able to inject html components in my main layout.

Example syntax:
```html
<body>
 {% include menu.html }
</body>
```
will add the whole content of the `menu.html` file.

**Tasks**

- [x] Detect when a component is needed
- [x] Read the content of the component file
- [x] Inject the whole content of imported component

**Duration:**

- Optimistic: 1h
- Pessimistic: 3h
- Expected: 2h

**Requirements:**
- #38
- #39

**Comment by vkaelin** [comment]
Already done by #39.
Closing this.
