### ISSUE TITLE
HTTP server

### ISSUE THREAD

**Issue by Marinlestylo** [dil-classroom/projet-friedli_jaquier_kaelin_pavicevic#42]
**Description:**

As a user, I would like to be able to create or lauch a local web server using for example java's standard library.
You should specify the port in the parameters

**Tasks**

- [x] Find a lib that helps to create the web server
- [x] Make a function that can create and/or load the web server
- [x] Choose a port on which the server will communicate
- [x] Document your work
- [x] Make tests that try to communication with the server ( GET request for example)

**Duration:**

- Optimistic: 1h
- Pessimistic: 2h30
- Expected: 1h45

**Requirements:**
- None
