### ISSUE TITLE
Static site rebuild on file change

### ISSUE THREAD

**Issue by Lazzzer** [dil-classroom/projet-friedli_jaquier_kaelin_pavicevic#55]
**Description:**

As a user, I would like that the build and serve commands rebuild the static site automatically when changes happen on the filesystem.

Hint : The ``WatchService API`` is a standard Java library that can be useful for this task.

**Tasks**

- [ ] Create a ``--watch`` flag for both commands
- [ ] Refactor build command
- [ ] Refactor serve command

**Duration:**

- Optimistic: 1h30
- Pessimistic: 3h30
- Expected: 2h30

**Requirements:**
- #43
